version: '3.7'
services:
  app:
    image: webdevops/php-nginx-dev:8.1
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DEBUGGER: xdebug
      UPLOAD_MAX_FILE_SIZE: 20M
      POST_MAX_SIZE: 21M

  db:
    image: postgres:13.1
    volumes:
      - db_data:/var/lib/mysql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    restart: unless-stopped

  redis:
    image: redis:5.0.5

  node:
    user: "node"
    image: node:14.16.1
    volumes:
      - ./:/app:cached
    working_dir: /app

volumes:
  db_data:
